### ISSUE TITLE
error in creation of nodes when updating a pipe

### ISSUE THREAD

**Issue by 3nids** [qwat/qwat-data-model#100]
This is another side effect of adding a vertex to a pipe on a node insert/move.

Basically, if you truncate a pipe (remove one of its ends), this will call create new node which call update the pipe. So you're trying to update the pipe geometry while actually editing it.

Here is the minimum steps to reproduce:

    -- add a distributor
    INSERT INTO qwat_od.distributor (id, name) VALUES (1, 'Demo Distributor');
    
    -- add a district
    INSERT INTO qwat_od.district (id, name) VALUES (1, 'My district');
    
    -- add a consumption zone
    INSERT INTO qwat_od.consumptionzone(id, name) VALUES (1, 'A consumption zone');
    
    -- add a pressure zone
    INSERT INTO qwat_od.pressurezone (id, name, fk_distributor, fk_consumptionzone) VALUES (1, 'A pressure zone', 1, 1);
    
    -- add a pipe between two nodes (1 and 2)
    INSERT INTO qwat_od.pipe (id, fk_node_a, fk_node_b,
           fk_function, fk_installmethod, fk_material, fk_distributor, fk_precision, fk_bedding,
           fk_status, fk_watertype,
           geometry) VALUES (1, 1, 2,
           101, 101, 101, 1, 101, 101, 101, 101,
           st_setsrid('linestring(530000 138260 0, 530001 138260 0, 530002 138270 0)'::geometry, 21781));
           
    update qwat_od.pipe SET geometry = st_setsrid('linestring(530000 138260 0, 530001 138260 0)'::geometry, 21781);

I don't see any solution to this at the moment.
I deactivated the trigger on my db for the moment

@mhugo any lead would be apprreciated!

**Comment by 3nids** [comment]
Here is the message: `ERROR:  tuple to be updated was already modified by an operation triggered by the current command
HINT:  Consider using an AFTER trigger instead of a BEFORE trigger to propagate changes to other rows.`

**Comment by 3nids** [comment]
I tried to use pg_trigger_depth() but it's not enough to say from where it is triggered.

The solution would be that when running function `fn_create_node` from trigger `ft_pipe_geom` (which is called on pipe insert/update), we do not try to update the same pipe.
Would there be a way to know what is the current root SQL command?

**Comment by mhugo** [comment]
@3nids EXPLAIN ANALYZE gives the call stack of triggers, but only when no error is encountered ...
I think the only way is to add raise notice in each trigger to understand what happens ...

I have this so far
<pre>
NOTICE:  in ft_pipe_geom
NOTICE:  in ft_pipe_node_type
CONTEXTE : instruction SQL « UPDATE qwat_od.pipe SET geometry = ST_Snap(geometry, NEW.geometry, 1e-6) WHERE ST_Distance(geometry, NEW.geometry) < 1e-6 »
fonction PL/pgsql qwat_od.ft_node_add_pipe_vertex(), ligne 6 à instruction SQL
instruction SQL « INSERT INTO qwat_od.node (geometry) VALUES (ST_Force3D(_point)) RETURNING id »
fonction PL/pgsql qwat_od.fn_node_create(geometry), ligne 7 à instruction SQL
fonction PL/pgsql qwat_od.ft_pipe_geom(), ligne 8 à affectation
NOTICE:  in fn_node_set_type
CONTEXTE : instruction SQL « SELECT qwat_od.fn_node_set_type(_node_id) »
fonction PL/pgsql qwat_od.fn_node_set_type(integer[]), ligne 12 à PERFORM
instruction SQL « SELECT qwat_od.fn_node_set_type( node_ids ) »
fonction PL/pgsql qwat_od.ft_pipe_node_type(), ligne 20 à PERFORM
instruction SQL « UPDATE qwat_od.pipe SET geometry = ST_Snap(geometry, NEW.geometry, 1e-6) WHERE ST_Distance(geometry, NEW.geometry) < 1e-6 »
fonction PL/pgsql qwat_od.ft_node_add_pipe_vertex(), ligne 6 à instruction SQL
instruction SQL « INSERT INTO qwat_od.node (geometry) VALUES (ST_Force3D(_point)) RETURNING id »
fonction PL/pgsql qwat_od.fn_node_create(geometry), ligne 7 à instruction SQL
fonction PL/pgsql qwat_od.ft_pipe_geom(), ligne 8 à affectation
NOTICE:  in fn_node_set_type
CONTEXTE : instruction SQL « SELECT qwat_od.fn_node_set_type(_node_id) »
fonction PL/pgsql qwat_od.fn_node_set_type(integer[]), ligne 12 à PERFORM
instruction SQL « SELECT qwat_od.fn_node_set_type( node_ids ) »
fonction PL/pgsql qwat_od.ft_pipe_node_type(), ligne 20 à PERFORM
instruction SQL « UPDATE qwat_od.pipe SET geometry = ST_Snap(geometry, NEW.geometry, 1e-6) WHERE ST_Distance(geometry, NEW.geometry) < 1e-6 »
fonction PL/pgsql qwat_od.ft_node_add_pipe_vertex(), ligne 6 à instruction SQL
instruction SQL « INSERT INTO qwat_od.node (geometry) VALUES (ST_Force3D(_point)) RETURNING id »
fonction PL/pgsql qwat_od.fn_node_create(geometry), ligne 7 à instruction SQL
fonction PL/pgsql qwat_od.ft_pipe_geom(), ligne 8 à affectation
ERREUR:  la ligne à mettre à jour était déjà modifiée par une opération déclenchée par la commande courante
ASTUCE : Considérez l'utilisation d'un trigger AFTER au lieu d'un trigger BEFORE pour propager les changements sur les autres lignes.
</pre>

**Comment by 3nids** [comment]
The path is as follows:
update pipe set geometry = XXXX where id = 1
calls the function trigger ft_pipe_geom
assign/create new nodes for fk_node_a and fk_node_b
which creates a new node in this case (since we removed the first or last vertex of the pipe)
INSERT INTO node .....
which calls the function trigger ft_node_add_pipe_vertex
which tries to update any pipe intersecting at node position
there it tries to update the pipe geometry since the node will be located at a vertex of the pipe

hence we're trying to update the geometry in a trigger triggered bit the geometry change

**Comment by 3nids** [comment]
I hope it's clear :)

**Comment by 3nids** [comment]
the idea would be to detect when we are already updating the pipe geometry.
otherwise, doing an after trigger for ft_pipe_geom does not sound like a good idea to me.
apart from this, no clever idea (yet ;) )

**Comment by mhugo** [comment]
Just to understand: why not an after trigger ?

**Comment by 3nids** [comment]
ft_pipe_geom is actually modifying the whole row, so an after trigger would lead to a new update command.

**Comment by 3nids** [comment]
fixed in a84c289620ee328b6856116bc3934fd693a126f6
