### ISSUE TITLE
moving node (installation, valve, etc) away from a pipe end will fail

### ISSUE THREAD

**Issue by 3nids** [qwat/qwat-data-model#108]
If you move a node from an end of pipe (a valve or an insallation for instance), this will cause an error.
This is another side effect of the automation of vertex addition to pipe.

I created a test to reproduce the error
https://github.com/qwat/qwat-data-model/blob/master/tests/test_move_node_end_pipe.sql

@mhugo can you or someone else from Oslandia have a look to this?

**Comment by 3nids** [comment]
ERROR:  tuple to be updated was already modified by an operation triggered by the current command
    HINT:  Consider using an AFTER trigger instead of a BEFORE trigger to propagate changes to other rows.
    CONTEXT:  SQL statement "UPDATE qwat_od.pipe SET	fk_node_a = qwat_od.fn_node_create(ST_StartPoint(geometry)) WHERE fk_node_a = OLD.id"
    PL/pgSQL function qwat_od.ft_pipe_node_moved() line 5 at SQL statement
    SQL statement "UPDATE qwat_od.node SET ......

**Comment by 3nids** [comment]
I believe the problem is that 2 triggers are run which will update the same pipe in this particular case: `qwat_od.ft_node_add_pipe_vertex` and `qwat_od.ft_pipe_node_moved` will be triggered on geometry update on `qwat_od.node`, although both triggers are `AFTER`

**Comment by ponceta** [comment]
Seems that Sébastien found it yesterday too. :

![image](https://cloud.githubusercontent.com/assets/8614223/13675637/de354352-e6e2-11e5-983b-36e065bf9ecd.png)

**Comment by vpicavet** [comment]
Do you have a SQL script that triggers the error ?

**Comment by 3nids** [comment]
Link in the description ;)

**Comment by vpicavet** [comment]
indeed ;-)
Will add to tasks list

**Comment by sylvainbeo** [comment]
The SQL test script is working here. No errors. I tried it a lot. Still works.
I'm going to have a look at the triggers anyway.

**Comment by 3nids** [comment]
I just tried again on a fresh install, just run this test and got the same error....
```
ERROR:  tuple to be updated was already modified by an operation triggered by the current command
HINT:  Consider using an AFTER trigger instead of a BEFORE trigger to propagate changes to other rows.
CONTEXT:  SQL statement "UPDATE qwat_od.pipe SET	fk_node_a = qwat_od.fn_node_create(ST_StartPoint(geometry)) WHERE fk_node_a = OLD.id"
PL/pgSQL function qwat_od.ft_pipe_node_moved() line 5 at SQL statement
```

which postgres do you run? I am running 9.3.11

**Comment by sylvainbeo** [comment]
I'm running 9.4. What do you mean by a fresh install ? You mean after running the init_qwat.sh a new DB ?

**Comment by 3nids** [comment]
Yes I meant running init + test script.
This is truly weird you don't get any error.
Can you try activate the test on travis to see if it passes there?

**Comment by 3nids** [comment]
@sylvainbeo @vpicavet any news on this?

**Comment by sylvainbeo** [comment]
Sorry, i was off the last week. Working on it now.

**Comment by sylvainbeo** [comment]
Not found yet. But the problem is the same king of https://github.com/qwat/qwat-data-model/issues/100 .
By the way, reproducing the problem via SQL is ok. Via Qgis is not. With qgis, when i move the the valve, it's the geometry_alt1 wich is modified, and not the geometry itself. Why is that for ?

**Comment by sylvainbeo** [comment]
I think i got it : 
https://github.com/qwat/qwat-data-model/pull/118

**Comment by ponceta** [comment]
Solved right? Should be closed then.
