### ISSUE TITLE
Integrating the possible diameters for PE standards

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#11]
Hi,

I'm now working in integrating in the vl_pipe_material table the standard diameter possibilities.

There will be 266 new values (136 for PE100 and the rest for PE80) I would like to know if you have any advice in what ranges should the id's be assigned to.

Currently, the PE values range between 5501 and 5603, so there's no space there.
I'm thinking of simply going from 6000 upwards.

What do you think, Denis?

PS. This also will manage to keep the current work-flow the same as we can easily bypass having too many options in the combo boxes values by restricting the material table in qgis with a query. (e.g. id < 6000).

**Comment by 3nids** [comment]
Hi,
There is a readme for the value list IDs
https://github.com/qwat/qwat-data-model/tree/master/02_valuelists
I assigned 1000 ids for the pipe materials. Having a look at the list, you should go for 7xxx.

Regarding customization of value list usage, there is a *vl_active* field in each value list table. You can choose which you want to use, and then filter in QGIS with ```vl_active = 't'```.

**Comment by tudorbarascu** [comment]
Nice, I'm currently working on it.
As currently when referring to Polyéthylène we are actually referring to Polyéthylène 100 I can put in the value_fr column Polyéthylène 100 and leave in the short_fr the "PE". I did the same for the romanian values and maybe you also want the full material name in the value_fr.

All the best

**Comment by 3nids** [comment]
sounds perfect to me!
