### ISSUE TITLE
 Implementing Z interpolation in model

### ISSUE THREAD

**Issue by vpicavet** [qwat/qwat-data-model#111]
Pipe geometry interpolation should be implemented in the model.

see qwat/QWAT#112

**Comment by haubourg** [comment]
PSC 10 06 decision that there is no  need for a tool dooing on the fly interpolations doing network editing. 
Interpolation can be made using survey points AND/OR DEM following the use cases.

**Comment by haubourg** [comment]
Please reopen if the need occurs again later
