### ISSUE TITLE
 Add SQL methods to revert changes ( undo history feature)

### ISSUE THREAD

**Issue by vpicavet** [qwat/qwat-data-model#112]
As filled in qwat/QWAT#116 we would like a feature to undo changes, and this needs SQL methods for reverting a change.

 We should list here the revert actions needed. Add your inputs in comment and I'll update the list.
- [ ] ...

**Comment by vpicavet** [comment]
For reference, this follow discussion on logs ( qwat/QWAT#77 )

**Comment by mhugo** [comment]
In complement, I will be working on methods to **replay** a change. In complement to qwat_sys.if_modified_func.

**Comment by haubourg** [comment]
Done in PR #155.
