### ISSUE TITLE
Valve exit node

### ISSUE THREAD

**Issue by sylvainbeo** [qwat/qwat-data-model#125]
Valve should be exited from nodes (to simplify data model and triggers, and for a better management)

**Comment by tudorbarascu** [comment]
any reason why valves in particular?

**Comment by sylvainbeo** [comment]
There was a discussion with Denis about that feature. Valves are not necessary nodes. They can be on a middle of a pipe for example. Other node objects cannot. Moreover, it simplifies some part of the models (triggers). Devs has already been made (see valve_exit_node branch)

**Comment by tudorbarascu** [comment]
Thanks for the info.

**Comment by ponceta** [comment]
Fixed by https://github.com/qwat/qwat-data-model/pull/127

Main point of release 1.1.0

https://github.com/qwat/qwat-data-model/releases/tag/1.1.0

Can be closed
