### ISSUE TITLE
[2.0.0] Date for release

### ISSUE THREAD

**Issue by ponceta** [qwat/qwat-data-model#132]
Hi all, @qwat/board 

What are the remaining points before next release? Which deadline could we have for this? We mentionned 15-17.11.2016 at the last meeting and there are still several PR pending. I'm a bit in a december rush yet and I think it's the case for all of us but QWAT 2.0.0 is the milestone for production in Pully.

**Comment by ponceta** [comment]
Pully goes on prod on 1.1.0.

**Comment by haubourg** [comment]
Hi Arnaud, 
Remaining work is:
- consolidate history viewer part. It works now as a generic extension and qgis plugin. Hopefully I can close the 2 Pending PR today and push a new one for QWAT. Upstream PR is already done here https://github.com/2ndQuadrant/audit-trigger/pull/26

- trigger simplification. @sylvainbeo is on it, it's a bit of recursive complexity to simplify, not so easy. That part will anyaway be transparent on the data and the qgis project. Hopefully it will be done by the end of the week (I know we said that twice already, sorry again)
