### ISSUE TITLE
QwEP (qwat enhancement proposal) @qwat/psc

### ISSUE THREAD

**Issue by ponceta** [qwat/qwat-data-model#142]
@haubourg what about an @qwat/psc for technical decisions? since @qwat/board has not much success for these kind of issues?

**Comment by ponceta** [comment]
Labelling and assignation of issues could be delegated to these kind of people!?

**Comment by haubourg** [comment]
Good idea. board has not had much success since very few issues were discussed also. Let's keep trying.

**Comment by haubourg** [comment]
Team created. I hope I did not forget anyone.

**Comment by ponceta** [comment]
@haubourg Maybe you missed @tudorbarascu, :) IMHO there's no point adding people to such a group if they haven't at least once comment something on github or strongly manifest their interest in following github's notification flux.

The purpose of such a group is also to be able to vote and decide about technical decisions which will be taken.

**Comment by haubourg** [comment]
@ponceta well, if some are present to physical meeting, and do not have yet contributed to Github, I still hope they will. BTW, it's only a shortcut to notify contributors faster than listing them one by one
