### ISSUE TITLE
Cleanup update scripts

### ISSUE THREAD

**Issue by haubourg** [qwat/qwat-data-model#144]
@sylvainbeo @3nids 
in update, we have old scripts that do not seem to have been updated recently such as

migrate.sh
upgrade.sh
upgrade_newinstallation.sh

They are not mentionned in the readme and it is unclear what is the difference between upgrade and upgrade_db. 

Can we cleanup things here?

**Comment by 3nids** [comment]
yes, go ahead.

**Comment by sylvainbeo** [comment]
Cleaned in upgrade branch
