### ISSUE TITLE
Update to 1.2.X Travis failing

### ISSUE THREAD

**Issue by ponceta** [qwat/qwat-data-model#152]
I do not have Travis happy about updating to 1.2.1.

See : https://github.com/VilleDePully/qwat-data-model/pull/6

and 

https://travis-ci.org/VilleDePully/qwat-data-model/builds/209741650

I see actually that tags are not keeped from github in forks. Are these Tags used in update or initialization scripts? Because it would explain why my compatibility checks and db initialization are failing.

**Comment by sylvainbeo** [comment]
Well, what a strange error. I think i've tried this before and it worked.
I will check again with fork.

**Comment by ponceta** [comment]
https://github.com/VilleDePully/qwat-data-model/pull/7

**Comment by ponceta** [comment]
Travis still failing on fork. @sylvainbeo Do you know if there's a way to get original tags on a fork?

**Comment by tudorbarascu** [comment]
Currently, this outputs the `0.1.0` model
```
git clone --recursive https://github.com/qwat/qWat
cd qWat/data-model
psql -U postgres -c 'create database qwat'
./init_qwat.sh -p qwat -s 21781 -d -r
```

**Comment by haubourg** [comment]
Issue confirmed. We need to add a commit to QWAT > data-model and data-model > metaproject each time a child module is updated. 
@sylvainbeo can you share the right process into https://github.com/qwat/QWAT/blob/master/doc/developer.rst ?

**Comment by ponceta** [comment]
This has been fixed. Thanks everyone. I pushed two lines to let trace of this in the doc.
