### ISSUE TITLE
generalize DB versioning conformity check

### ISSUE THREAD

**Issue by 3nids** [qwat/qwat-data-model#153]
currently checking the conformity is done by shell scripts which are in the current repo. These are tightly coupled to qwat db architecture.

The idea is to move the scripts out of qwat DB repo and generalize them so they could be reused by other similar projects.

The script would be move in its own repo.
A README would describe how it works:
* how it works,
* how many db you need
* where is stored the current version of the model (in the DB)
* how/where write the deltas
* clarify how a new version is brought (by a git tag?)
* pre/post scripts (shell, python)

PARAMETERS:
There would be a single configuration file (YAML?) specifying the following. A template would be provided.
* current DB service
* upgrade DB service
* table where is stored the current version
* optional pre/post migration scripts (such as drop/write views as in qwat)
* options for data sample loading and pushing to the repo

FEATURES: 
The same functionality as present now would be ported plus:
* checking the upgrade path: be sure not to miss any minor release (e.g. 1.2.0 -> 1.2.1 -> 1.3.0 and not directly 1.2.0 -> 1.3.0). For this, shall we keep track of all updates in the DB (instead of one line  qwat_sys.version, keep all migrations with their dates).
* cross platform
* test upgrades with demo data
* output upgraded demo data and push it to its repository when upgrade is merged (or tagged ?) so that is stays inlined with DB version

A dedicated test in qwat-data-model would call the script in the submodule

Let's try to make it as simple and clearer as possible!

Proposed name for the module: pg_versioning_conformity_checker ? could not find any shorter/better atm.

**Comment by haubourg** [comment]
concerning the name, I would avoifd pg_versioning since it is referring to data existing versioning tools. 
What about pg_model_upgrade_conformity_checker?

**Comment by haubourg** [comment]
@sylvainbeo  
 We need to estimate how much time would be required for that task (who will do the work is undetermined). Can you do that once the cleanups and the demo data integration in scripts is done?
 @m-kuhn ping here, do you have any opinion on that, since that could also benefit to QGEP.

**Comment by m-kuhn** [comment]
Sounds like a good plan. This is a good functionality to align between different modules.

Maybe it's not only the DB checks but also the migration path (e.g. dialogs that guide through the update).

> pre/post scripts (shell, python)

Shell scripts are not portable (windows), I'd say better stick to python

-----

For reference, drupal also has such a system

When you upgrade your installation, the workflow is

 1. code is updated (plugin)
 2. after an update, the plugin version is compared to the db version
 3. if there are missing patches, a warning is shown (with a link to the update dialog)
 4. The user is asked to make a backup (extra points if it's a one-click solution or done automatically)
 5. the update dialog lists the missing patches (Version 020105 (2.1.5) -> 020106 (2.1.6): Add new field to cache labels qgep.wastewater_structure._label) for review
 6. The updates are applied in order.
 7. A report with warnings and errors from the database is shown

**Comment by sylvainbeo** [comment]
We have to ADD also the configuration for Updating a potential DEMO backup.

**Comment by sylvainbeo** [comment]
The current script is not complex. We have encountered some issues because of missing commands or bad SQL for cheking the conformity. But the process stay simple (to me).

**Comment by sylvainbeo** [comment]
Time estimation.

I would say beetween 5 and 10 days to have a functionnal script / repository.

- create the repo
- write the documentation
- copy the functionnalities
- lots of tests
- discussions about the functionnalities

Cleaning and upgrade scripts are almost done. It remains only the data-sample update (which is functionnal with my account, but we have to create a generic account, still waiting information from Carlos to do that).

**Comment by m-kuhn** [comment]
@sylvainbeo , @3nids can you give some pointers towards the current situation (where are the scripts in questions, which scripts do what, what should be kept, what should be rewritten)
CC @marioba

**Comment by sylvainbeo** [comment]
On each commit, travis execute that main script :

https://github.com/qwat/qwat-data-model/blob/master/update/verify_upgrade_db.sh

It mainly check that the commit is coherent (modifications made on the DB model vs delta files, check the documentation http://qwat.readthedocs.io/en/latest/upgrade.html to know how the delta files are managed). 

It also updates the data demo sample with the lastest model version.

**Comment by marioba** [comment]
Hello to all,
I'm doing some tests to verify the proper functioning of flyway to handle qwat db versions.
I started with the dump of the db created by init_qwat.sh version 1.0.0 and then I added the delta files from qwat-data-model/update/delta as migration files with flyway and compared it with the db created directly by qwat 1.2.6, and for now all seems to work fine. 

There is one thing I'm not clear, can you explain what the purpose of the audit_trigger_row and audit_trigger_stm is? In the delta file 1.2.2 those triggers are deleted, but if I create the db directly with 1.2.6 they are there...

Thank you.

**Comment by 3nids** [comment]
theses triggers come from the [audit trigger](https://github.com/qwat/qwat-data-model/blob/master/system/audit.sql), some were deleted in 1.2.2 to enable the triggers on the views rather than on the tables.

**Comment by marioba** [comment]
I'm developing some python scripts based on current shell scripts, independent from qwat architecture:

- **checker**, python script that compare 2 db for differences
  - based on the queries from test_migration.sql
  - don't uses external tools like diff

- **upgrader**, python script that apply a delta to a db
  - Flyway-like features e.g. log and checksum of the applied upgrades

- **dumper**, python script to backup a db
  - uses pg_dump

These scripts are independent of qwat and can be used in other projects without modifications

In addition, I am preparing a **main interface** (with a config file) for managing specific qwat upgrade procedures using the developed scripts, for example:
1. create db_test
2. backup db_prod and copy in db_test
3. apply delta to db_test
4. compares db_test with latest version init_qwat.sh
5. apply delta to db_prod
6. apply post script
7. ...

I think Monday I'll post a first version so that we can proceed with accurate tests.
Remarks are welcome.

**Comment by marioba** [comment]
I've committed some things in the db_manager branch. It's still work in progress, especially I'm still working on the script _manager.py_ and on the unit tests. Soon I will also do some integration tests with Travis.
If you want, have a look and tell me what you think...

**Comment by haubourg** [comment]
Thanks @marioba ! 
@sylvainbeo, can you make some code review on that?

**Comment by sylvainbeo** [comment]
Good job. I like the checker. Did you re-write the SQL or just pick it from the test_migration.sql ?

**Comment by marioba** [comment]
Thanks for the feedbacks.
@sylvainbeo I pick the queries from test_migration.sql with just a few small changes to make them generic and independent from qwat.

**Comment by marioba** [comment]
In the db_manager branch I committed the latest changes with several improvements including:
- possibility to define in the checker what to check or not
- completion of the manager
- integration with Travis

It seems to work and at the moment I dont'have any open points.
Please tell me what do you think and if I need to modify something...

**Comment by m-kuhn** [comment]
Thanks a lot @marioba looks great!

> possibility to define in the checker what to check or not

How is this done? A configuration file?

* I think the plan is to separate the conformity checker from this repository (so we can also use it for qgep or other data models). Is this just moving the folder `db_manager` or is there more to it?
* What kind of errors did you check, can you provide a short list of errors that it was able to detect
* Then, finally I'd say let's go for a pull request where it's easy to review and comment

**Comment by marioba** [comment]
Thanks @m-kuhn.

Some things are explained in the [README](https://github.com/qwat/qwat-data-model/blob/db_manager/db_manager/README.md) of db_manager. 
To use this tool in another project like qgep, you need to modify only the manager.py script (+ config yaml file). The other scripts you can use in other projects without modifications.

The checker script checks and informs about differences between two databases for the following elements:

- tables
- columns
- constraints
- views
- sequences
- indexes
- triggers
- functions
- rules

You can specify as optional argument of the script (or in the db_manager config file) if you want to ignore some of these checks.


I created a [pull request](https://github.com/qwat/qwat-data-model/pull/190)

**Comment by m-kuhn** [comment]
What is your opinion on splitting the generic scripts into a separate repository?

Then we have one authoritative place where we integrate bugfixes etc. Projects like qwat, qgep, etc can then add a `git submodule` or `git subtree` to integrate the generic scripts into their sourcecode while keeping a link to the common repo.

**Comment by marioba** [comment]
Yes, I think it's a good idea.

**Comment by marioba** [comment]
I refactored several things, implemented @m-kuhn suggestions and moved the project into a new repository. It's now [here](https://github.com/opengisch/pum)
I'll soon make some some tests to use it in qwat as a submodule.

**Comment by haubourg** [comment]
Nice thanks! 
I asked @sylvainbeo for a review soon

**Comment by m-kuhn** [comment]
We yesterday had an internal presentation of pum and it looks really good, thanks @marioba . Would be great if we could test this with either qwat or qgep in the next weeks.

**Comment by marioba** [comment]
I done the integration of [pum](https://github.com/opengisch/pum) in qwat. In the branch [db_manager](https://github.com/qwat/qwat-data-model/tree/db_manager) I configured Travis to:
-  create 3 db:
   - _qwat_prod_
   - _qwat_test_
   - _qwat_comp_
- restore a dump file created from qwat 1.0.0 into _qwat_prod_
- set the baseline version of _qwat_prod_ to 1.0.0
- run the `init_qwat.sh` script into _qwat_comp_ to be used as reference
- set the baseline of _qwat_comp_ to 1.2.8
- run pum's `test-and-upgrade` command to upgrade the _qwat_prod_ db after testing the procedure on _qwat_test_
- run a final check for differences between _qwat_prod_ and _qwat_comp_

It works fine except that it found some differences in the views (and therefore on columns, indexes, rules, ...) because they are apparently not generated from the delta files. 

I think for this we need to first decide how we want to manage the creation of the views (see the discussion [here](https://github.com/opengisch/pum/issues/4) ) and then fix the deltas of qwat according to what we decide, to correctly create all the views.

**Comment by sylvainbeo** [comment]
Great. 
Indeed the views are  generated by a script after (in the original integration process, the comparison is done without the autogenerated views, because we consider that if all the tables are corrects, then the views will be).

**Comment by m-kuhn** [comment]
It would be good to have a **pre-all** and **post-all** script. This will help to drop any view that we ever created and only recreate the ones that we really need with the latest update.

**pre-all.sql**

```
-- List of all views that ever existed and could theoretically be present in the current DB.
DROP VIEW IF EXISTS qwat.some_view0;
DROP VIEW IF EXISTS qwat.some_view1;
DROP VIEW IF EXISTS qwat.some_view2;
```

**post-all.py**

```
... calls some scripts that will create the latest views, based on current release.
```

**Comment by haubourg** [comment]
I have been asked by @varrieta if PUM could allow to do migrations on existing database on a windows server running postgres, or even run it from an separate linux machine. 
I didn't see any issue with that by lookiong at the code. I found no git or createdb dependency. Do you confirm PUM could be used to manage distant migrations ?

**Comment by marioba** [comment]
Yes, everything should work remotely. Connections information are taken from the services set in .pg_service.conf file.

**Comment by haubourg** [comment]
Thanks @marioba !

**Comment by haubourg** [comment]
@marioba can you change your pum_integration branch so that we target 1.3.0 version in delta file and baseline process? This is pure marketing stuff, but important for the general board to follow us. Thanks!

**Comment by marioba** [comment]
@haubourg Done and pull requested https://github.com/qwat/qwat-data-model/pull/202

**Comment by haubourg** [comment]
thanks @marioba !

We're almost done I think. I looked at the travis failures with PUM activated on your last PR. 
It seems 1.2.8 dropping view and recreating them after the delta is again the culprit. I should push a pre and post file to solve that ?

**Comment by marioba** [comment]
Yes, I think removing the views with a pre-all file and recreate them in a post-all file will solve the problems.

**Comment by sylvainbeo** [comment]
pre-all file won't work. I just made tests, and with the current travis.yml, it can't work because some deltas are interacting with the views...

So i think we need to apply a pre to the 1.2.8 delta only

**Comment by sylvainbeo** [comment]
> Message from DropViews: Dropping views: done
OK
     Applying delta 1.0.0... OK
     Applying delta 1.0.1... OK
     Applying delta 1.1.0... relation "qwat_od.vw_export_installation" does not exist
LINE 273:         FROM qwat_od.vw_export_installation

**Comment by haubourg** [comment]
Agreed, from my understatement, only 1.2.8 needs to drop views before applying the patches. 
If dropping all views before in the old upgrade script, I had the same error for 1.1.0 patch

**Comment by m-kuhn** [comment]
So...

pre-script.py:

    if upgrade_from <= 1.2.8:
        nothing
    else:
        drop views

1.2.8.sql:

   drop them views

**Comment by sylvainbeo** [comment]
@m-kuhn Mmmm. I would rather do a  pre_1.2.8_xxx.py than having a pre-all with conditions.

**Comment by m-kuhn** [comment]
That would mean introducing advanced filter logic in the file naming?

I'm not sure this is the right level to solve such a problem. That might also lead to very complex naming (Deliberate and shameless exaggeration: `1.2.8_to_2.6.2_except_1.2.9_and_2.6.1.py` ;) )

For me, the pre-1.2.8 requirement to have the views around while migrating should be treated as an exception which I'd rather have solved in qwat with tools that are around rather than in a new feature on pum level.

**Comment by sylvainbeo** [comment]
@m-kuhn  There's a misunderstanding there i think. PUM already includes the pre deltas files behaviour. 
 That's what i was saying. I create a delta_1.2.8_xxxx.pre.py wich will be play just before the 1.2.8 delta.

**Comment by m-kuhn** [comment]
Sorry, I'm still at a loss. Which script will drop the views so they are absent when upgrading from 1.3.0 to 1.3.1?

**Comment by sylvainbeo** [comment]
Arf. You're absolutely right. My bad. I was forgetting that we could update from a version to another (i was thinking to the travis verification test).

**Comment by sylvainbeo** [comment]
See https://github.com/qwat/qwat-data-model/pull/205

**Comment by haubourg** [comment]
Ok guys, I think PUM creation process is done. Let's clos that and open new tickets in case of issues or new features. Well Done !
