### ISSUE TITLE
Hydrant model inf sup

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#178]
Hello,

I was looking at hydrant model sup/inf values.
Are the inf ones supposed to be the underground models and the sup ones supposed to be for the 
"on the ground" ones?

I noticed there except the normal autre, inconnu and  a determiner values there are others common values like Hawle, Hawle_H4, Hinni, VonRoll.

Does it make sense to you to merge these into one table that has a boolean "underground" column to make things simpler?

**Comment by tudorbarascu** [comment]
Comments in https://github.com/qwat/qwat-data-model/pull/179/commits/f19038e9d360107a22f12729482d38df0194c6f5

**Comment by tudorbarascu** [comment]
Just noticed ``fk_model_sup`` and ``fk_model_inf`` are both set to not null in the hydrants table.
This means they stand for something else then what I imagined as a hydrant cannot be underground and on the ground at the same time, right?
Can someone shed a light on this?

**Comment by 3nids** [comment]
this is for above ground hydrants. They have two parts: the one under the ground, and the one above. Combinations of models is possible, hence the two fields.

**Comment by tudorbarascu** [comment]
@3nids Thanks for the info.
So, as a summary it would seem we have the following cases:
* underground hydrant
* above the ground hydrant (single model)
* above the ground hydrant (combination of two parts/models)

**Comment by tudorbarascu** [comment]
Taking another look at this, how is this supposed to model underground hydrants (which don't have two parts, at least here in Romania). Do you have underground hydrants made of two parts?
If not, then the data model should be enhanced as it currently enforces two parts also for the underground hydrants (with the NOT NULL constraints on both ``fk_model_sup`` and ``fk_model_inf`` columns).

I would like to propose that we drop the NOT NULL constraint for the ``fk_model_sup`` and add a CHECK constraint that still enforces the two part model for the case where the hydrant is above the ground.
This way we keep the current CHECKS except for the underground model which is single part.

Does it make sense to you @qwat/qwat-psc ?

**Comment by tudorbarascu** [comment]
Something like this would suffice if we drop the ``fk_sup_model``:
```
ALTER table qwat_od.hydrant ADD CONSTRAINT above_ground_hydrant_has_2_parts_check check (
(fk_model_sup IS NOT NULL OR underground IS TRUE) -- If the hydrant is above ground fk_model_sup should be filled
);
```

This proposal considers the undergound hydrant to be tied to the ``fk_inf_model`` and does leave the possibility that the underground hydrant can be composed of two parts(models).

However, if we reach a consensus in that there's no two part underground hydrant, we can also enforce that all the underground hydrants should have ``fk_sup_model`` NULL.
