### ISSUE TITLE
data model typos

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#182]
``change sanitization_chlorine_gazeous`` to ``sanitization_chlorine_gas``

Also,
``number_of_pipe`` should also be ``number_of_pipes`` as one can think it as pipe id (tag nr.)  -- in ``qwat_od.vw_pipe_schema`` and ``qwat_od.vw_pipe_schema_merged``

**Comment by tudorbarascu** [comment]
Any thoughts on this?

**Comment by ponceta** [comment]
:+1:  (nice to have).
