### ISSUE TITLE
pipe protection SOMO value

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#184]
Hello,

Does anyone know what does ``SOMO`` stands for  (in qwat_vl.pipe_protection, SOMO PE, SOMO PVC, SOMO autre)?

**Comment by ponceta** [comment]
SOMO tablet? Probably some switzery, I did not found any of these in the canplast catalog. @3nids you sure know better?

**Comment by ponceta** [comment]
Ok, I was not so far from it.

SOMO stands for an old professionnal term (probably an old brand from canplast?) like actual gresintex http://www.canplast.ch/cataloguenew/pdf/ft_2.pdf

It's indeed a hard plastic protection pipe Pe for cables and PVC for water and wastewater.

**Comment by ponceta** [comment]
Voici la réponse de Canplast à qui j'ai posé la question.

```
Bonjour,
 
SOMO est une ancienne marque disparue du groupe Bouygues qui ne caractérisait pas vraiment un type de tuyau, même si, dans la mémoire collective des années 80-90, cela voulait plutôt désigner, à tort, les tuyaux PE-câbles… 
 
A votre disposition pour plus de renseignements…
 
Meilleures salutations,
 
Solutions durables pour la gestion des eaux
Didier Lièvre
```

@tudorbarascu does this clarify your question?

**Comment by tudorbarascu** [comment]
Yes!
