### ISSUE TITLE
Tag 1.2.7

### ISSUE THREAD

**Issue by ponceta** [qwat/qwat-data-model#186]
Hey, tomorrow morning I'll update my datamodel to 1.2.7

@3nids @haubourg Is it possible for one of you to tag https://github.com/qwat/qwat-data-model/commit/91968743a30b3334dbc10cffa4d02625c697eac8 as 1.2.7 release please!

This would be very nice from you!

**Comment by haubourg** [comment]
Hi, I'm having two days off tomorrow and friday, I won't be able to make it by tonight. 
In my understanding 1.2.7 only adds the export views for remote by now

**Comment by ponceta** [comment]
I'll use the commit as tag for my update :) It can be done later.

**Comment by ponceta** [comment]
Not relevant anymore. 1.2.7 was just removing vw_export_remote
