### ISSUE TITLE
Ménage dans git

### ISSUE THREAD

**Issue by ponceta** [qwat/qwat-data-model#208]
Un coup de poutze dans git serait le bienvenu, ne serait-ce que de supprimer les branches mergées.

Ceci alourdit considérablement le repo et donc le trafic/stockage sur toutes les instances clientes et serveurs.

Actuellement https://github.com/qwat/qwat-data-model/ pèse 31.31MB à chaque clonage complet.

**Comment by ponceta** [comment]
(et sans metaproject)

**Comment by haubourg** [comment]
31Mo c'est pas si lourd. QGIS c'est combien déjà ? ;-)

**Comment by haubourg** [comment]
I removed about 10 old branches.

**Comment by 3nids** [comment]
le nettoyage c'est toujours bien pour y voir clair, malheureusement un repo git ne verra jamais sa taille diminuer à moins de réécrire le git log en forçant, et ça c'est pas une bonn idée!

la taille du repo git vient entre autre du fait qu'à une époque les fichiers de trad de toutes les langues étaient commités tous les jours (~15mo/jour)....

**Comment by ponceta** [comment]
@3nids j'ai vu en effet que la taille n'était pas impactée en effet.

@haubourg Merci, je pense que c'est une bonne pratique de garder le minimum d'anciennes branches de travail, il me semble d'ailleurs qu'il est toujours possible de les restaurer le cas échéant.
