### ISSUE TITLE
How to simply rewrite views?

### ISSUE THREAD

**Issue by ponceta** [qwat/qwat-data-model#221]
What syntax do you use to quickly rewrite views using :

https://github.com/qwat/qwat-data-model/blob/master/ordinary_data/views/rewrite_views.sh ?

ping @3nids

**Comment by sylvainbeo** [comment]
@ponceta Doesn't work for you ?

**Comment by ponceta** [comment]
@sylvainbeo no, since I'm not on the server, I have to specify which pg_conf it should adress

In my pg_service.conf I have:
#qwat_dev
[qwat_dev]
#enter your database ip
host=postgis2.pully.ch
#database name
dbname=qwat_dev
port=5432
user=postgres
password=xxxxxxxx

and I get 

```
(tutorial-env) pulmexa@ubuntu:~/qwat-data-model$ ./ordinary_data/views/rewrite_views.sh -v -s 21781 -p qwat_dev
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

Because it's not the gentle way to talk to it!

**Comment by elemoine** [comment]
Some comments:

As far as I can see the `rewrite_views.sh` script doesn't have options. So the `-v`, `-s` and `-p` options that you use have no effect.

The Postgres service that you want to use (from your `.pg_service.conf` file) can be specified through the PGSERVICE environment variable. For example, if you want to use the `qwat_dev` service you'll use this:

```bash
$ export PGSERVICE="qwat_dev"
$ ./ordinary_data/views/rewrite_view.sh
```

`rewrite_view.sh` itself does not use `PGSERVICE`, but [`insert_view.sh`](https://github.com/qwat/qwat-data-model/blob/master/ordinary_data/views/insert_views.sh) does.

**Comment by elemoine** [comment]
I realize that the `SRID` env var should also be set, so:

```bash
$ export SRID="21781"
$ export PGSERVICE="qwat_dev"
$ ./ordinary_data/views/rewrite_view.sh
```

**Comment by ponceta** [comment]
@elemoine Thanks! Is there a simple way to set env variables at start?

I've added some aliases in my .bashrc to switch between pg services.

**Comment by ponceta** [comment]
Set default env. variables.

My use case would be :

Starting Ubuntu, launching terminal, move to the corresponding folder, (change some environment variables if needed), execute ./ordinary_data/views/rewrite_view.sh or any useful shell script

Or don't you recommend such an approach?

**Comment by elemoine** [comment]
@ponceta if `PGSERVICE` and `SRID` are set in your `.bashrc` then you can just open a terminal and execute `rewrite_view.sh`. That should work. You can also open a terminal, overwrite `PGSERVICE` and/or `SRID` (as shown above) and execute `rewrite_view.sh`. Create your own scripts as described by @sylvainbeo is also an option.

**Comment by ponceta** [comment]
Thank you both @sylvainbeo @elemoine 

I want to test the SIRE update https://github.com/qwat/qwat-data-model/pull/217

That's why I need to be able to rewrite all views.

I need to customize a bit to be able to override my views (export_pipe_sigip, ... ) 

This is issue is solved. I'll open a new one if there's anything.

Could maybe be reported in https://github.com/qwat/QWAT/blob/master/README.rst

**Comment by 3nids** [comment]
sorry for not getting involved earlier.
I wouldn't recommend setting PGSERVICE on system startup as this could be dangerous... Having to explicitly define it might avoid some complete DB removal...
