### ISSUE TITLE
Plan for 1.3.2 release

### ISSUE THREAD

**Issue by haubourg** [qwat/qwat-data-model#238]
Hi all, 
we have had quite a lot of changes recently, I'd like to plan the 1.3.2 release if possible. 

I need a confirmation that the SIRE extension is ready for production. I merged it today, Denis gave me a GO. 

:question:  Any objection to release a 1.3.2? 

We have some work being done in the data model customization area that could enter 1.3.3, it requires a PUM update to allow multiple delta file directories. This will adress #151

Here is the temporary changelog : 

# Infrastructure changes

- Various Travis fixes and enhancements (Use PGSERVICE , stop build on error)
- Implement delta file ordering to allow several delta files on each version. This will make is easier to 
plan semantic versions without retaining pull requests for too long
- Deactivate auditing during migrations - fixes #248 "Update delta files and bulk loading need a way to deactivate audit log triggers"
- Changes to make QWAT compliant with all Linux / UNIX OS's
- Various Travis fixes and enhancements (Use PGSERVICE , stop build on error)
- Missing spatial indexes for some qwat_od's tables
- Missing SRID declaration for some views
- Fix dump options for data-only demo dump for release process

# Business logic changes

- Implement SIRE export extension and adds the extension environement variable system.  delta_1.3.2_005_update_sire_code_material.sql - fix #237 code sire for PE 100 
- Adds in Core value list missing SIRE column for remotes
- add PE material for diam 800, 900 and 1000, SDR 11, PN 16
- add PREMO 1000 material
- added delta for big PE diameter value + adduction
- add PE mat for big diameters (800 -> 2500) SDR 21, pn 8
- add PE mat for big diameters (800 -> 2500) SDR 26, pn 6
- add pipe function adduction value 
- Add pipe protection values for PE, PVC and Steel pipes 
- Improve Survey points : added  foreign key to fk_object_reference to object_reference table, add geometry index, add `Total station` as type of survey points

**Comment by lbartoletti** [comment]
+ Fixes views #239

**Comment by lbartoletti** [comment]
- A backup with only the structure will be released (cc @elemoine )

**Comment by haubourg** [comment]
1.3.2 has been released today :)
