### ISSUE TITLE
vl_pipe_function

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#24]
The column name is "major", and the inserts are made with "major_pipe".
Should I provide a small fix with major or with major_pipe?
Also, what are you using major for? 

Regards

**Comment by 3nids** [comment]
I use this to have a bit more flexibility for small scales maps.
There are two fields in the function: schema_visible determines if the pipe will be visible at small scales, while major determines if the pipe is considered as important or not (for symbology).
For instance, pipes for hydrants are considered as major but are not printed at small scales.
I think the symbology is clearer  now (I mean the tree hierarchy of the symbology).
Thanks for your PR.
