### ISSUE TITLE
Plan for 1.3.3 release

### ISSUE THREAD

**Issue by haubourg** [qwat/qwat-data-model#250]
# Changelog:

## Bug fixes
 - fix xxxx

## Features
- feature

## Supported versions of tools

    >= postgres 9.6.6 (travis)
    >= Python 3.5.5 (travis)
    >= pum 0.6.7
    >= pip 9.0.1 (travis)
   >=  QGIS  2.16

**Comment by ponceta** [comment]
#250 Need the metaproject to be updated.

**Comment by lbartoletti** [comment]
# Infrastructure changes
- `PUM`: update to last version
- `metaproject`: update to last master
- Add customizations
- `upgrade_db.sh` now accepts multi delta dir (customizations and extensions)
- Change `upgrade_db.sh` to avoid re-creating the roles 
- Update sire extension

# Bugfixes
- Add SRID in od_valve: Fix #187
- Fix `valve_count` for `pipe`
- Fix and update metaproject: add missing ELSE statement in installation_update and delete functions
- Add some FR and EN translations for installation part value list
- Fix dump at release. Views wasn't exported in 1.3.2
- Fix decimal value in `pipe_material.sdr`
- Add 'IF NOT EXISTS' on CREATE TABLE qwat_od.damage
- Add `fk_precision`, `fk_precisionalti` and `fk_object_reference` to `cover`

# Business logic changes
- `qwat_vl.valve_function`: add for vent valve the J value for the `short_fr` attribute, as it is the case for other
- Add 'Compteur de chantier' for `part_type` and EN/RO translations
- Add 25 as default pressure norminal for 'Fonte' in `pipe_material`
- Extend ro values for `hydrant_output` and `hydrant_models` + comment the `hydrant_models` table
- Remove FALSE default for hydrant underground and marked
- Changing the constraint logic on the "year" columns of the `pipe` table
- Add consistency on PRIMARY KEY creation procedure

**Comment by lbartoletti** [comment]
# Changements d'infrastructure :
- `PUM` : mise à jour sur la dernière version
- `metaproject` : mise à jour sur la version courante
- Ajout des personalisations
- `upgrade_db.sh` accepte plusieurs répertoires (personalisations et extensions)
- Changement d'`upgrade_db.sh` pour éviter de recréer les rôles
- Mise à jour de l'extension sire

# Corrections :
- Ajout du SRID dans od_valve: Corrige #187
- Correction de valve_count pour pipe
- Correction et mise à jour du metaproject: ajout des ELSE dans les functions `installation_update` et `delete`
- Ajout de quelques traductions FR et EN pour les listes de valeur d'`installation part`
- Correction des dump lors des release. Les vues n'étaient pas exportées en 1.3.2
- Correction des décimales dans `pipe_material.sdr`
- Ajout de 'IF NOT EXISTS' sur `CREATE TABLE qwat_od.damage`
- Ajout de `fk_precision`, `fk_precisionalti` et `fk_object_reference` sur `cover`

# Changements métier :
- `qwat_vl.valve_function`: ajout de la valeur 'J' dans la colonne `short_fr` de "vent" comme pour les autres
- Ajout de 'Compteur de chantier' pour `part_type` et traductions EN/RO
- Ajout de la valeur 25 par défaut pour `pressure norminal` pour 'Fonte' dans `pipe_material`
- Extension des traductions RO pour `hydrant_output` et `hydrant_models` + commentaire de la table `hydrant_models`
- Suppression de la valeur FALSE par défaut pour `hydrant underground` et `marked`
- Changement de la logique de la contrainte sur les colomnes "year" de la table `pipe`
- Ajout de cohérence sur les clés primaires lors de la procédure de création
