### ISSUE TITLE
Valves have no FME readable geometry

### ISSUE THREAD

**Issue by ponceta** [qwat/qwat-data-model#265]
Since my update in qwat 1.3.1, I can't use qwat_od.valves correctly in FME since their geometry are not "FME" readable.

![image](https://user-images.githubusercontent.com/8614223/43267281-d37fe298-90ed-11e8-9ddc-d5155b1c043a.png)

Def of my qwat_od.valve table :

https://gist.github.com/ponceta/101c03969088e559897010738437f27f

Has anyone encountered this?

**Comment by haubourg** [comment]
Hi  @ponceta I just tested and FME seems to consider the `geometry` filed as an attribute, so confirmed yes. 
If I change the reader inserting a simple select like this: 
![image](https://user-images.githubusercontent.com/1629853/43321739-1a7295c8-91ad-11e8-85f9-1002be42cd5d.png)
then FME reads correctly the geometries. 

I tested using a full SQL statement excluding the 2 other alternative geometry fields and it works. 

````
select id, geometry,  "_geometry_alt1_used",
"_geometry_alt2_used",
"_pipe_node_type",
"_pipe_orientation",
"_pipe_schema_visible",
"_printmaps",
"_schema_visible",
"altitude",
"closed",
"diameter_nominal",
"fk_distributor",
"fk_district",
"fk_folder",
"fk_handle_precision",
"fk_handle_precisionalti",
"fk_locationtype",
"fk_maintenance",
"fk_object_reference",
"fk_pipe",
"fk_precision",
"fk_precisionalti",
"fk_pressurezone",
"fk_printmap",
"fk_status",
"fk_valve_actuation",
"fk_valve_function",
"fk_valve_type",
"handle_altitude",
"id",
"identification",
"label_1_rotation",
"label_1_text",
"label_1_visible",
"label_1_x",
"label_1_y",
"label_2_rotation",
"label_2_text",
"label_2_visible",
"label_2_x",
"label_2_y",
"networkseparation",
"orientation",
"remark",
"schema_force_visible",
"update_geometry_alt1",
"update_geometry_alt2",
"year",
"year_end"
from qwat_od.valve
````

It seems FME gets confused between the geometry columns. When creating the reader, I see the three geometry columns as attributes. It might be an FME issue.

**Comment by ponceta** [comment]
@haubourg Thanks! I've raised this in https://knowledge.safe.com/content/idea/30260/postgis-reader-should-handle-multiple-geometry-col.html

**Comment by ponceta** [comment]
If any more interest see https://knowledge.safe.com/articles/24702/handling-data-that-contains-multiple-geometry-colu.html for FME and reopen if anything's needed.
