### ISSUE TITLE
Feature: Consider using valve as lines or other ways to better show their situation in the field

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#27]
A profile perspective of the field situation.
![imgo](https://cloud.githubusercontent.com/assets/3179646/6958948/720a6200-d91b-11e4-9054-ab7dd554a552.jpg)

In QGIS, it looks like:
![qgis](https://cloud.githubusercontent.com/assets/3179646/6958980/0ad02452-d91c-11e4-81ca-c7bf4e81168d.png)

But when going in the field, as you can only see the top of the valve in the ground, you are led to believe the junction of the two pipes is on the right of the valve (when in fact is on the left of the valve).

Thoughts?

**Comment by 3nids** [comment]
I think it that additional geometries could be used for that.
You could define that head is main geom while you use the additional one for the handle.
Then, it's gonna be easy to represent this as you want on the map.

What do you think?

**Comment by tudorbarascu** [comment]
I also thought to do it more or less as you suggested.
What I haven't figured out is the editing part as this would mean the work would be done on two QGIS layers, wouldn't it?
Suggestions?

**Comment by 3nids** [comment]
Yes, you need to duplicate the layer (at least for now, maybe later we'll have multiple geometry support).
But it's not that bad, you can name it "valve handles".
Basically the workflow is:
- add a valve with geometry
- select this valve in the other layer (so it has a NULL geometry)
- use "add part map tool" to add a point for the hanlde

**Comment by tudorbarascu** [comment]
I watched yesterday "multiple geometry" ping-pongs in the mailing list and it seems the multiple geometry support opinions are split.
At least for now, I think that it's easier and safer to depict valves with two point lines. The line origin is the origin of the handle and the line end is the position on the pipe. Any spatial query would only take into consideration the end of the line.
Basically, I don't see any caveats.
Thoughts?

**Comment by tudorbarascu** [comment]
I thought about this a little more and the easiest way for now is to add a new geom_line column.
Will work on it today/tomorrow. Will also make trigger so that when adding/updating the line, it's end point is written in the geom (point) column. Viceversa, when the point geom is edited and the geom_line is not null, the changes should be reflected in the geom_line column.

Will start working on it today/tomorrow.
If you have any other suggestions until I make the merge request they are very welcomed.
All the best,
Tudor

**Comment by 3nids** [comment]
Hi,
What about adding just a second geometry as a point for the handle? Therefore it could be NULL.
Also, if you want to display lines, you can easily make a view using the 2 point geometry columns.
What do you think?

**Comment by tudorbarascu** [comment]
That's also very good (you nailed it in your first post actually, nice).
It's indeed better. Will do it like that.
Have a nice evening!

**Comment by tudorbarascu** [comment]
Closed by https://github.com/qwat/qwat-data-model/commit/fa5af55b8fe9ca007603510fea94acd4b6a6f8c8
