### ISSUE TITLE
views are not exported since v1.3.2

### ISSUE THREAD

**Issue by lbartoletti** [qwat/qwat-data-model#270]
Import qwat_v1.3.2_data_and_structure_sample.sql or qwat_v1.3.2_data_and_structure_sample.backup
![image](https://user-images.githubusercontent.com/7521540/44842750-fac98880-ac46-11e8-8b8e-66a162ce3f29.png)

works well with v1.3.1
![image](https://user-images.githubusercontent.com/7521540/44842942-66abf100-ac47-11e8-81a8-11ffcac5404d.png)

cc @elemoine

**Comment by elemoine** [comment]
I just created new dumps using [.deploy/create_release.py](https://github.com/qwat/qwat-data-model/blob/master/.deploy/create_release.py), and I confirm that the views are there after importing the data_and_structure_sample dump. So to me there's no bug the script that creates the dumps.

When 1.3.2 was released maybe the dumps were manually uploaded. And maybe the uploaded dumps were created from a qwat database that did not have the views (for some reason).

Anyway, I uploaded new data_and_structure_sample dumps on the v1.3.2 release page. They should ok this fine, but I would be good if someone could verify it.

**Comment by voanhtam** [comment]
Hi, 
I'm having trouble restoring the v1.3.2 data and structure sample backup file.

I've got postgis 2.3.3 install with posgresql 9.6

When i'm restoring (with pg_restore) i've got this error : 
![image](https://user-images.githubusercontent.com/15107399/46585711-507a2780-ca74-11e8-9c6f-95099566025f.png)

After checking the function in postgis 2.3.3 the function is : **st_curvetoline(geometry,integer)**
but the backup file is about an **st_curvetoline(geometry, double precision)**

**Comment by ponceta** [comment]
@voanhtam please open a new issue if you encounter such problematics.

Has anyone tested this in 1.3.3 pg 9.6?

**Comment by lbartoletti** [comment]
It works for me. Tested with postgis24 and postgresql96.

`pg_restore -U postgres --dbname qwat -e --no-owner --verbose --jobs=3 --disable-triggers --port 5432 qwat_dump.backup qwat_v1.3.3_data_and_structure_sample.backup` (Requires to add users qwat_viewer, qwat_user, qwat_manager)
![image](https://user-images.githubusercontent.com/7521540/50891361-647b4f80-13fc-11e9-9b69-cd454a6cf2e9.png)
