### ISSUE TITLE
Adding a pipe between two 3d nodes should import their altitude

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#281]
- a pipe should have the same altitude of the starting 3d vertex as the starting node.
- a pipe should have the same altitude of the ending vertex as the end node

**Comment by ponceta** [comment]
Is it not the case actually?

![image](https://user-images.githubusercontent.com/8614223/48695636-eb236580-ebdf-11e8-9b7c-fb04c566712c.png)

Pipes are LINESTRINGZ and nodes are POINTZ, so at creation (not update), when you snap on POINTZ with your LINESTRINGZ in QGIS 2 and 3, you should get the snapped Z value as default value for Z value on snapped vertices.

Node:
![image](https://user-images.githubusercontent.com/8614223/48696193-7cdfa280-ebe1-11e8-89c7-0d1a6e91d45e.png)

PipeVertex:
![image](https://user-images.githubusercontent.com/8614223/48696205-85d07400-ebe1-11e8-8758-935bf7ed72e3.png)

**Comment by tudorbarascu** [comment]
Indeed, from QGIS side it is, not from the model (database) side though. I had some expectations that it would be from the db side also (observed while doing migration tests). I think it we think it should be from QGIS side we can close this.

**Comment by lbartoletti** [comment]
> not from the model (database) side though

Personally, I think that you're right, we need to focus a thick database approach.

**Comment by ponceta** [comment]
@tudorbarascu Do you have any needs in this direction? (edition database side, to be accessed from other clients)?

If not I suggest to close this.

I don't have this use case since our only edition tool is QGIS actually.

**Comment by tudorbarascu** [comment]
I don't have any needs so I'll close it. Our editing tool is also only QGIS. I would have preferred the logic be enforced db side but this can be in the future when other more important things are done.
@arnaud-morvan @lbartoletti Thank you for your remarks.
