### ISSUE TITLE
Incorrect join in qwat_od.vw_export_meter view

### ISSUE THREAD

**Issue by kandre** [qwat/qwat-data-model#288]
I think that the view qwat_od.vw_export_meter view has an incorrect join between qwat_od.district and qwat_od.vw_element_meter:
`LEFT JOIN qwat_od.district district ON vw_element_meter.fk_pressurezone = district.id` 
In my opinion it should be changed to:
`LEFT JOIN qwat_od.district district ON vw_element_meter.fk_district = district.id`

Accordingly export_meter.py should probably be adapted from:
https://github.com/qwat/qwat-data-model/blob/b1126d31f6bb42b757abdc53474b82fe6dbfaefc/ordinary_data/views/export/export_meter.py#L26
to:
`fkey: fk_district`

**Comment by haubourg** [comment]
good catch @kandre. Ping us if you need us to propose a pull request

**Comment by kandre** [comment]
@haubourg I guess in this case a delta should be written ?

**Comment by haubourg** [comment]
@kandre yep, a PR for the core model associated with a delta file to migrate the existing databases. 
If you need help to write your own PR, that would be a pleasure too!

**Comment by ponceta** [comment]
In QWAT, there's no need to create deltas on views. Just fix the reference in the right export view generation file. See #293 for Fix.

This has just to be added to the bugfixes for next release.

**Comment by kandre** [comment]
Ok, good to know, thanks.
