### ISSUE TITLE
Table and foreign key for construction sites

### ISSUE THREAD

**Issue by ponceta** [qwat/qwat-data-model#296]
Proposition:
Add Table for construction site and foreign key in pipe, valves, surveypoints and hydrants.

Idea : 
Identify the elements impacted, created or modified by a construction site.

![image](https://user-images.githubusercontent.com/8614223/54186651-2b1e9900-44ac-11e9-8593-0fc8a4b3d455.png)

Table : Construction Site 
id (serial)
identification (varchar (40))
localisation (text ())
start_date (date ())
end_date (date ())
remark (text ())
the_geom geometry(MultiPolygon,$SRID),

foreign key in: 
pipes
network elements
valves
surveypoints

**Comment by haubourg** [comment]
@ponceta would there be any link between a construction site area and the so called folders in QWAT?

**Comment by ponceta** [comment]
Indeed. That's exactly what I needed and described...

CREATE TABLE qwat_od.folder
(
  id serial NOT NULL,
  identification character varying(50) NOT NULL,
  description text,
  date_start date,
  date_end date,
  geometry_polygon geometry(MultiPolygon,21781),
  geometry_line geometry(MultiLineString,21781),
  CONSTRAINT folder_pkey PRIMARY KEY (id),
  CONSTRAINT folder_identification UNIQUE (identification)
)

@haubourg Thanks!
