### ISSUE TITLE
work in progress - for water status

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#306]
Hi,

In the ``qwat_vl.status`` table for projects we do have:
```
INSERT INTO qwat_vl.status (id, active, functional, code_sire, value_en, value_fr, value_ro, description_en, description_fr, description_ro) VALUES (1306, false, false, NULL, 'project',        'projet',       'Proiect',      '', 'L''objet est un projet validé en attente ou en cours de réalisation.', 'Obiectul face parte dintr-un proiect care se va face sau în curs de realizare. ');    /*  */
```

Basically, the work in progress status currently resides in the "project" status and there's no way to know which projects have already started.

Do you think that we should add a "work in progress/in execution" status and optionally remove the meaning "en cours de réalisation" for the "project" status?

We have big projects that are currently in execution and they will be so.. for almost an year..let's say. There's currently no way in the base model to distinguish those and I think it would be helpful.

Of course, this could stay in a custom model but I was wondering if it makes sense to you to have it in the base model.

**Comment by haubourg** [comment]
Hi, 
I'd be +1. 

@ponceta  @lbartoletti  Any idea if QGEP and VSA standard already holds such life cycle information. I'b in favour of a model convergence if possible.

**Comment by sjib** [comment]
This is what is implemented in QGEP: We distinguish the two statuses:

other.project

 INSERT INTO qgep_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (2,198,6529,'wastewater_structure','status','**other.project**','other.project','','weitere.Projekt','N','**autre.projet**','PR','altri.progetto','','alta.proiect','','yyy_Konkretes Bauprojekt vorhanden oder in Ausführung (im Bau). Bei Absicht Status "geplant" verwenden. Nach Abschluss des Baus Wechsel auf Status "in_Betrieb".','Konkretes Bauprojekt vorhanden oder in Ausführung (im Bau). Bei Absicht Status "geplant" verwenden. Nach Abschluss des Baus Wechsel auf Status "in_Betrieb".','Lorsqu’un projet de construction concret existant est exécuté','Esiste un progetto definitivo o il manufatto è in costruzione. Nel caso di intenzione di realizzazione utilizzare lo stato "pianificato". Ad opera realizzata cambiare lo stato in "in_funzione".','Stare care se mentine pana cand proiectul va fi executat.');


other.planned

INSERT INTO qgep_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (2,198,7959,'wastewater_structure','status','**other.planned**','other.planned','','weitere.geplant','G','**autre.planifie**','PL','altri.previsto','','rrr_weitere.geplant','','','','','','');

**Comment by tudorbarascu** [comment]
So.. can I make a pull request as it seems we all agree?

**Comment by lbartoletti** [comment]
+1 for me

> So.. can I make a pull request as it seems we all agree?

Yes, please.
