### ISSUE TITLE
Hydrant materials

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#31]
Hi Denis,

Here we have a need to store the hydrant material (+ diameter). Are you also interested in this so I can make a pull request? For. instance we have Hydrants of Fonte diameter 65, 80 and 100.
Currently, you're only differentiating the hydrants by model, right?

All the best,
Tudor

**Comment by 3nids** [comment]
It would be indeed interesting to have a more precise description for the hydrants.
There is another user who's interested.
Would you be able to list here what you would like, so we can discuss.
I will ask the other to participate.
Thanks a lot.

**Comment by tudorbarascu** [comment]
In Romania we only use hydrants of Fonte, diameter 65, 80 and 100.
As a temporary solution, we're adding a fk_material field that points to the pipe materials with fk, and in the form, instead of a value relation we're using a value_map with 
5001, 5352, 5369 and 5371 values of the pipe materials.
Thoughts?
