### ISSUE TITLE
Leaks improvement to designate repairing team

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#32]
Hi,

Regarding the leaks, we have a need to add the repairing team in the leaks data-model/ui. 
Are you interested in this feature so that I can make a pull request?
As always, any suggestions are welcomed.

All the best,
Tudor

**Comment by 3nids** [comment]
go for it.

I would suggest that we have a table of workers that might be available for specific works (leaks repairing for instance, and later valves checking, and so on)
They would have a date_entry and date_end.

So we don't have something specific for leaks.

thanks

**Comment by haubourg** [comment]
Hi, @tudorbarascu  can we close that issue since it has been merged more than a year ago?

**Comment by tudorbarascu** [comment]
Yes, it was left open as a reminder to discuss possible enhancements on maintenance, see https://github.com/qwat/qwat-data-model/pull/43

I had some ideas (lost my notes) at that time regarding maintenance. While waiting for the newcomers to join the discussion, somehow we passed on.
