### ISSUE TITLE
`qwat_od.network_element: fk_locationtype as array []?

### ISSUE THREAD

**Issue by nicolas-sitylb** [qwat/qwat-data-model#324]
Hi,

is there any reason why the key `fk_locationtype` in table `qwat_od.network_element` is of type `integer[]` (array)?
Isn't it a little bit "dangerous", as a foreign key, to be of that type, especially regarding the defined set of distinct values in `qwat_vl.locationtype`?

Thanks for your enlightenment.

**Comment by ponceta** [comment]
I think there was originaly the use to define multiple selection : (sand + cubic street stones, ...)

If needed, a better location_type definition should be set : ex. bedding, filling, covering (which makes many attributes to fill).

**Comment by tudorbarascu** [comment]
@ponceta Yes. that's the intention. When a field describing something can have multiple values at the same time... we go array. One downside is that PostgreSQL isn't supporting yet Foreign Keys on arrays.
