### ISSUE TITLE
Fitting table proposal

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#33]
We also have a need to add pipe fittings to our model.
Are you interested in this feature?

Thus, at pipe endings, pipe intersections we have existing fitting types:

- elbow fittings
- end fittings
- reduction fitting
- T connector
- unknown (proposed for the table)

The- intersection above should be depicted by the fk_type.

Other columns that we thought of except id and fk_type are:
fk_status
date (maybe just year)
remark

What do you think?

**Comment by 3nids** [comment]
I think these should be handle in qwat_od.part
You can add your own there.

**Comment by tudorbarascu** [comment]
Indeed, many thanks, it slipped passed me.
I will also make a pull request.

All the best
