### ISSUE TITLE
Installation type completion with chambre de branchement/raccord?

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#34]
Hi again,

We have some situations where the installation building is not a valve chamber but a raccord/branchement one.

Should I also make a pull request on this one? If so, how do you want it to be named, short_fr included?

**Comment by 3nids** [comment]
I think this is somehow specific to your case.
I would recommend that you add this value on your owm after the import.
You should give it a code > 10'000 so it can be seen that it's a custom value.

**Comment by tudorbarascu** [comment]
Thanks for the info
