### ISSUE TITLE
The view vw_export_pipe is always in crs 21781

### ISSUE THREAD

**Issue by tproduit** [qwat/qwat-data-model#350]
The scripts which generates this view doesn't take into account the crs set by the user. It always set the crs as 21781.

**Comment by ponceta** [comment]
![Screenshot_20220216-130015474.jpg](https://user-images.githubusercontent.com/8614223/154260472-3ff6cf67-1f1d-4d99-b6ae-91f5b332f4be.jpg)

This is indeed hard coded and should be using the SRID stored either in the database or SRID supplied as parameter !
