### ISSUE TITLE
Consider the "Emplacement"-- site, of the water objects

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#36]
For some objects: hydrants, valves, installation building we have a need of adding l'amplasement.
It's interesting to know if the object is located in:
- carrossable (carriageable)
- trottoir (sidewalk)
-  gravier (gravel)
- beton (concrete)
- terre
etc.

Is this specific also to your case?

Regards,
Tudor

**Comment by 3nids** [comment]
We don't use them.
Also, I wouldn't mind having them in the schema...

For another project, we are starting defining the form using json. This will an easy customization of forms and used fields.

**Comment by tudorbarascu** [comment]
Good,
I will make a pull request when they're ready and I would also like to put them in the UI's.
If you think they're going to crowd the ui's, I though of hiding them in the ui and start them using code (as we already use some code to enhance the user input workflow) or just to keep them to our specific project.

All the best!
