### ISSUE TITLE
Valve refactoring regarding valve type, valve function & valve actuation

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#37]
Proposals:

- What do you think about adding a new field for valves (fk_valve_actuation) that corresponds to a valve_actuation table holding values depicting how the valve is handled:

- hand control
- electric drive
- remote controlled
- other
- unknown
- to be determined

Currently in the valve_type table the values refer to both type and actuation (actionnement).
As in practice we have a "limiteur de debit" that is remote controlled, the current data model is unable to present this situation as we can choose only one value at the same time.

- as we have the "vanne clapet" value in the function table, it seems more appropriate to send move it in the valve_type table

- it also seems more appropriate to us that a "purge" valve should be a  function, and not a type of valve

- We currently don't have an equivalent for the "ventouse" and "vidange-ventouse" values in the valve_function table and we simply put them to "FALSE" but if you could give more details on them maybe we can also integrate them in our model or give suggestions on them

As some things may be specific to Romania, what do you think?
Thanks,

Tudor

**Comment by 3nids** [comment]
As you noticed, these two lists are not really well defined.
It would be nice to clean up these and add your proposition.

* ok for the 2 moves: purge (type => function), vanne clapet ( function => type)
* ventouse:  have to check, it's somehow similar to purge for us
* vidange: used to empty a pipe by throwing the water away (to the river)
* vanne clapet: if we move it, would it make sense to have "backflow prevention" as a function then?
* ok to create the actuation table and remove "remote valve". from valve_type

**Comment by tudorbarascu** [comment]
- Yes, it does make sense to have a "backflow prevention" function.

We understood what the "vidange" function was for. We were a little unaware about the vidange-ventouse function, but we think we got it now:

- vidange: discharge/empty water function
- ventouse: empty the accumulated air
- vidange-ventouse: has both the above functions

Please say if you do not concurr with us on this.

**Comment by 3nids** [comment]
exactly!

**Comment by tudorbarascu** [comment]
How about the "vanne à gauche" that's currently in the type of valve?
Should it also go to the actuation table as a "left hand control" type?

**Comment by 3nids** [comment]
Not sure.
Wouldn't it be possible that a valve is left hand but also remotely actuated.
Then, wouldn't it be better as a boolean?

**Comment by tudorbarascu** [comment]
Yes, a boolean would be good for future-proofing the cases we don't know.
However, to my knowledge the rotation sense is only important for the hand control. If it's automatic it shoult not matter.
Your call.

**Comment by 3nids** [comment]
For left hand, not sure, if it would not make sense to keep it in types of valves.
These are actually quite old and it can be considered as a type.
Although it could be considered as a specialty for us?

Otherwise, I just pushed the other changes.
Missing is the actuation table. Do you have one ready?

**Comment by 3nids** [comment]
sorry, just saw your commit

**Comment by 3nids** [comment]
are you ok to rebase your commit?
otherwise, I can manually push it.

**Comment by tudorbarascu** [comment]
Yes, I had everything ready, was waiting for your last comments :). Give me 1 minute to add your last commits.

**Comment by 3nids** [comment]
sorry for that...

**Comment by tudorbarascu** [comment]
Don't worry. If we have colliding commits it means the project has life in it :).

**Comment by tudorbarascu** [comment]
Fixed by https://github.com/qwat/qwat-data-model/commit/df651cc2e425e370e6cdd68dfafbc238431930ee https://github.com/qwat/qwat-data-model/commit/4a551c84f792495ae9e1bdc64f70d27d14f982e8 and https://github.com/qwat/qwat-data-model/commit/7c525cb85268fcd28abf6efcbe377038bab947f3
