### ISSUE TITLE
Homogenize the "other", "unknown" and "to be determined" values

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#44]
I got a  good suggestion from a colleague that maybe we should add the "other", "unknown" and "to be determined" values in all the vl_tables. Moreover, he suggested to have the same values in each table, let's say to 10001, 10002, 10003. This would also make them appear in the end if the order is by id.
It's a good idea from my point of view. If this sound good to you I will make a pull request. Of course, maybe this change will imply  some loving regarding the qgs project if some styling/queries/expression are based on the unknown value from a table (can't tell by heard now). I will also search for "unkown" based possible problems in the project and run them through you if I make the pull request.
Opinions?

**Comment by 3nids** [comment]
this sounds good to me!

**Comment by tudorbarascu** [comment]
Ok, will make a pull request when it's ready

**Comment by tudorbarascu** [comment]
Resolved by https://github.com/qwat/qwat-data-model/pull/49 and https://github.com/qwat/qwat-data-model/pull/50
