### ISSUE TITLE
Database model

### ISSUE THREAD

**Issue by GeorgeMihai** [qwat/qwat-data-model#45]
Hello, 

I managed to implement the data model in Postgresql,  but could you tell me which model standard do you use for the database ? Thank you.

**Comment by tudorbarascu** [comment]
Hi,

This is the model standard for qWat attuned for the qWat contributors needs.
Please be more specific if you want more details.
Or as I see you're from Ro like I am, leave some contact details and I can maybe walk you through.

All the best,
Tudor

**Comment by GeorgeMihai** [comment]
Salut Tudor, 
Ma refer la standardul in vigoare dupa care e structurata baza de date?? (ex: VSA-DSS, SIA 405). Mai am si alte nelamuriri tehnice. Daca ai putea sa ma indrumi ti as fi recunoscator. Adresa mea de mail este: george_mihai_2005@yahoo.com, iar nr. de tel: 0740185257.
