### ISSUE TITLE
Proposal: change year constraint in order to consider 1800

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#53]
As I noticed in QGEP the 1800 year is the fallback option  (in case the user doesn't know what year that element has been put into function etc.) I suppose it would be good if we could do the same.

Thoughts?

**Comment by 3nids** [comment]
dates can be kept as null.
I don't think having 1800 is a good idea it could alter the calculation of the age mean without being noticed.

**Comment by tudorbarascu** [comment]
It's clear. Thanks
