### ISSUE TITLE
node altitude_dtm

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#57]
The altitude_dtm column from nodes suggests you're always getting the node altitude from the a DTM.
Do you sometimes need to use/use the actual node altitude (underground)? If so, is there a need for a "real" altitude column?

**Comment by 3nids** [comment]
Well, what about renaming it to altitude and fk_altitude_precision?

**Comment by tudorbarascu** [comment]
Really nice, will make a pull request later on

**Comment by 3nids** [comment]
doing it, no worries

**Comment by tudorbarascu** [comment]
thanks :)

**Comment by 3nids** [comment]
done in 47b22b43d04e345c9f8b0810de10134d03263696
