### ISSUE TITLE
Enhancement: Pipes should have vertex where they have a valve 

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#60]
I think it would be a good think that we have pipe vertices (and never nodes) where the valves intersect the specific pipe.
It would be easier for splitting pipes after valves in the hydraulic model.

**Comment by haubourg** [comment]
Hi, is it still required? 
IMHO Linear interpolation is far enough to split pipes. What is the need for having vertices ? 
Régis

**Comment by 3nids** [comment]
Actually it is already implemented.
