### ISSUE TITLE
qwat_od.ft_leak_geom() improvement

### ISSUE THREAD

**Issue by bogdanvaduva** [qwat/qwat-data-model#62]
Hi everybody,

Here is the problem that I had.
I have a leak which is reported to be on street A where I have a pipe A. The leak is near an intersection with another street (street B where I have a pipe B). The repair crew will dig on street A but will find out that the leak comes from pipe B. 
When I try to insert the leak on street A and select pipe B I found out that pipe B is deleted because of
the code:

NEW.fk_pipe            := qwat_od.fn_pipe_get_id(NEW.geometry);

I modified the trigger like this:

NEW.fk_pipe            := CASE WHEN qwat_od.fn_pipe_get_id(NEW.geometry) IS NULL THEN NEW.fk_pipe ELSE qwat_od.fn_pipe_get_id(NEW.geometry) END;

After that it worked fine.

Regards

**Comment by 3nids** [comment]
I would rather go for
```
IF NEW.fk_pipe IS NULL THEN
  NEW.fk_pipe := qwat_od.fn_pipe_get_id(NEW.geometry);
END IF;
```

**Comment by 3nids** [comment]
done in 177851a

**Comment by bogdanvaduva** [comment]
But I need the pipe id even if it's not found by qwat_od.fn_pipe_get_id(NEW.geometry).

**Comment by 3nids** [comment]
Well, in the propose approach, on insert, if you give a pipe (via the form) it will keep it. It will try to find one only if you didn't give it.

**Comment by bogdanvaduva** [comment]
I thought about what you proposed and I think that your approach is much better.
Thanks a lot.
