### ISSUE TITLE
installation building  object_reference and precisionalti

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#63]
I think the constraints should be non null only when altitude is not null.
Thoughts?
Will make a pull request later on if you're ok with it.

**Comment by 3nids** [comment]
in the new structure, these are all null allowed as they're on the node table.
Anyway, you raise a good point. I think I am going to decouple the node table with node (basic point) and object which inherits from node. In object we'll have all the constraints (fk_*).

(then installations, valves, hydrants, etc will inherit from object)

**Comment by 3nids** [comment]
done in 1066d07c5c36978dedab74166204ceadfb2b2225

**Comment by tudorbarascu** [comment]
Thanks!

**Comment by 3nids** [comment]
I think I'm almost there :)
