### ISSUE TITLE
Enhancement proposal: Add a "Demo Distributor" value in the datamodel

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#69]
I was just thinking about adding a "Demo Distributor" value in the distributors list so that the datamodel permits editing right away without having to create a distributor.
This would enable new users to test right away, without having to figure out that they should first add a value in the distributors table.
Thoughts?

**Comment by 3nids** [comment]
Excellent idea !

**Comment by 3nids** [comment]
What about creating a demo.sql file and you can enable it with option in initial_qwat.sh.
Therefore, we might want to add a bit more later.

**Comment by tudorbarascu** [comment]
It would also be cool :).
Shouldn't we also put some data in the `demo.sql` to live up to its name?

**Comment by 3nids** [comment]
Would be perfect. We can start with something minimalistic anyway

**Comment by tudorbarascu** [comment]
Added a "demo distributor value" in https://github.com/qwat/qwat-data-model/commit/46caee8936560f6859ebcd9b294acaad6ab87581 

This issue also relates with https://github.com/qwat/QWAT/issues/24

**Comment by 3nids** [comment]
I would avoid having this in the main files. If we have it in demo.sql then it can be used or not,  and then avoid the need to truncate tables before importing data for instance.
