### ISSUE TITLE
Valve function values

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#7]
Hi,
I want to append this line to the data model:

"INSERT INTO qwat.vl_valve_function (id, value_fr,value_ro)                      VALUES (6114,'vanne branchement','vană branşament');            /* 14      */"

In the current data model we already have the following value which may have the same purpose/meaning to you (I haven't figured it out):

"(id, value_fr, value_ro, schema_visible ) VALUES (6105,'organe abonné','','false')"

Could you please shed a light here?
Thanks,
Regards,
Tudor

**Comment by 3nids** [comment]
indeed, they would be the same. Maybe, we should rename 'organe abonné' by 'vanne de branchement'.

**Comment by tudorbarascu** [comment]
Ok, many thanks, maybe in the future  "organne reseau" should become "vanne de reseau".

**Comment by 3nids** [comment]
+1
