### ISSUE TITLE
Valve reworking

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#73]
Hi Denis,

Taking another look at the valves funciton, I still am unsure of:
- What's the difference between `jauge` and `ventouse` in the valve function values
- what's a `vanne d'ouvrage` 
- What's the `prise de secours` for

I guess we should have better valves grouping.

@schoeller Suggestions/opinions on the valve values from the function and types table would be welcomed.

**Comment by 3nids** [comment]
apparently jauge is used to limit the flow, while ventouse is for removing the air.
vanne d'ouvrage was meant for the ones in installations --removing this.
prise de secours iwas meant for emergency use (connecting to another network) -- removing this.
