### ISSUE TITLE
Rules with multiple commands are not working --> the node element doesn't get deleted

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#79]
Hi Denis,
I tried to rewrite the rule on ``vw_element_valve`` to no avail, and any test (like the following) doesn't work for any action other than the first:
```
CREATE OR REPLACE RULE rl_vw_element_valve_delete AS
    ON DELETE TO qwat_od.vw_element_valve DO INSTEAD
    
    (DELETE FROM qwat_od.valve WHERE valve.id = OLD.id;
     INSERT INTO counter (id) VALUES (100)
);
```
Digging further:

http://stackoverflow.com/questions/20216755/rule-with-multiple-commands

We should maybe change to triggers:
```
CREATE OR REPLACE FUNCTION qwat_od.ft_element_valve_delete()
  RETURNS trigger AS
$BODY$
					BEGIN
						DELETE FROM qwat_od.valve WHERE valve.id = old.id;
						DELETE FROM qwat_od.vw_node_element WHERE vw_node_element.id = old.id;
						--RETURN NEW;
					END;
					$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;


CREATE TRIGGER tr_vw_element_valve_delete
  INSTEAD OF DELETE
  ON qwat_od.vw_element_valve
  FOR EACH ROW
  EXECUTE PROCEDURE qwat_od.ft_element_valve_delete();
```

Hope I'll find an answer why the rules don't work as documented.

**Comment by 3nids** [comment]
I wouldn't delete the node automatically.
I would rather fire `fn_node_set_type(id)`to redefine it (and delete it if possible).

That could be easily done by adding a new rule, with a DO ALSO and running this command.

**Comment by tudorbarascu** [comment]
Indeed it sounds better.
I am still puzzled by the fact that the second action of the rule like it is now doesn't run.

**Comment by 3nids** [comment]
I think you can't run several command in a rule.
I had the same troubles.

**Comment by tudorbarascu** [comment]
According to their documentation, you can.
I also managed to run more than one commands (INSERTS only).
It's either a bug, or a misunderstanding from our side.

**Comment by 3nids** [comment]
some answer here http://grokbase.com/t/postgresql/pgsql-general/1145begqsr/problem-with-multiple-action-rule-on-modifiable-view

I will modify it to trigger!
