### ISSUE TITLE
cover enhancements/proposals

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#80]
Hi,
I was thinking of:
- adding a `fk_installation` cover so that we can attach covers to installations.
- for rectangular covers, it would be interesting of also having width, length, and rotation in order to have a rectangle symbol matching the actual cover projection
- I am inclined a little to ditch the node from covers. Although it isn't a real bother, it also doesn't feel right to have it as node as we have nodes for installations and the cover should be an installation child. In QGEP as cover is somewhat the main object, it makes sense.

Thoughts?

**Comment by tudorbarascu** [comment]
ping @3nids

**Comment by 3nids** [comment]
covers do not inherit nodes anymore, it makes sense.
I also added fk_installation

For the rest, wouldn't it be easier to have a second geometry polygon ?

**Comment by tudorbarascu** [comment]
Thanks.

A second polygon as geometry would also suffice.
I made the above proposal as I am a little uneasy with the current work-flow of adding a secondary geometry and I wanted to grasp your opinion on it.

My reasoning is that working with circle - diameter and rectangular (length, width + rotation) would actually save time when adding new covers with area presenting + decreasing storage needs.

I was also wondering about the existence of covers with shape different than that of a circle and rectangle. If so, we should drop the circular (boolean) and add a fk_form column for future proofing.
We of course have covers for hydrants that are oval shaped but I don't know if there will ever be a need to describe that.

**Comment by tudorbarascu** [comment]
Actually, to my knowledge, we only have square/circle shaped covers.
So, circular (boolean) with dimension and rotation would also be an option.

**Comment by tudorbarascu** [comment]
Regarding the ``circular`` column (with default ``true`` db side), do you think that we should change its type from boolean to integer (fk_form)?
This way we would have the unknown, to be determined .. values and we would also cover the rectangular form.
Indeed, if it's not circular, it should be rectangular.. so boolean seem to work.
However, the current process of adding a rectangular cover is too ..complex in that we add a cover, and as the default is true, we need to save it in the database and then uncheck the checkbox...

I will do a pull request if you concur.
Thanks

**Comment by tudorbarascu** [comment]
ping @3nids

**Comment by tudorbarascu** [comment]
Hello, while migrating I stumbled again on covers and the data model currently fits the bill but I think we can extend the covers to also have fk_precision, fk_precision_alti and  fk_object_reference (like before).
We could drop the NOT NULL on those if anybody is bothered by it.

Thoughts?

**Comment by tudorbarascu** [comment]
Everything should be good now. The only thing that we could have extra is to drop the circular (boolean) and add a ``fk_form`` column for future proofing cover forms as we now have logic for squared + circular but not for rectangular or oval or other shapes.
