### ISSUE TITLE
The future of 0 value altitude modeled as NULL one is not a bright one

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#82]
I think that water companies that cover locations close to the sea will probably be incompatible with altitude 0 being considered as NULL in the data model.
As they probably have values really close to 0 altitude (bigger or even smaller) it would be a show stopper for them so I guess we should change it to something else.
Thoughts?

**Comment by tudorbarascu** [comment]
Although the ST_Force_3D function adds a 0 by default to the z coordinate and it could raise feelings towards using 0 as a default z value, I feel that we still shouldn't follow that direction.

**Comment by 3nids** [comment]
I started with -9999, but as you noticed force3d set it to 0.
It makes things much more complex...

I would like to ask postgis dev if they have any plan on this topic.

**Comment by 3nids** [comment]
https://lists.osgeo.org/pipermail/postgis-users/2015-December/041054.html

**Comment by tudorbarascu** [comment]
Cool. I was thinking that we should just avoit the St_force3d and use a custom function instead.

**Comment by tudorbarascu** [comment]
@3nids I noticed there was no reply on the mailing list I though I would raise a ticket but it seems there's already one at https://trac.osgeo.org/postgis/ticket/3057

As a workaround I'm thinking about the possibility of temporarily enforcing a check constraint so that no vertex of the pipe has 0 altitude and that in the case that one should be inputed in the geometry we automatically transform it to to a value like -99999 and we consider that to be our NULL value until a solution arrives from upstream?

@vpicavet Any suggestions here?

**Comment by vpicavet** [comment]
@tudorbarascu The ticket does not help, it would only set the same z for all values.

Only solution would be to allow for z null values for vertices in PostGIS, but the use case should be pushed forward, not really sure if the idea would be accepted.

As for now 0 value is kept and documented here : 
https://github.com/qwat/QWAT/wiki/Elevation-in-qWAT

**Comment by haubourg** [comment]
Just FYI, default values for Z are coming in https://github.com/qgis/QGIS/pull/3905
And I dug esri specifications, default z value is 0.0. So it seems reasonable to start with a simple solution by now with the option for z default.

**Comment by m-kuhn** [comment]
What do you think about handling unknown Z values as `NaN` internally in QGIS and have a configurable *magic number* (like -9999) that the provider will map to if it doesn't support `NaN`?

I think that should be more transparent and future-proof.

**Comment by 3nids** [comment]
@m-kuhn indeed this seems much more reasonable.

**Comment by haubourg** [comment]
we have ticket #210 for better NaN Z handling. Let's close this one
