### ISSUE TITLE
Store model version in the data

### ISSUE THREAD

**Issue by vpicavet** [qwat/qwat-data-model#91]
We should have the model version written by default in the model itself.

Even if it is made initially for APIs, we should try to use Semantic Versioning : http://semver.org

We may also think about storing potential additional modules versions at the same place.

First question is where do we store this information ? In the settings table ? A specific table ?
Second is : do we have a simple way to integrate automatically this information into the model when doing a release ( with git tag ) ?

Advices welcome, @3nids @mhugo ?

**Comment by vpicavet** [comment]
See #104

**Comment by mhugo** [comment]
Hi, no strong preference for the storage of the version. Your #104 proposition seems good (except the broken unit test :) ). A key-value metadata table should be ok too.

Before having an automatic version, we can start with a small text file to read each time a new release has to be done that includes "don't forget to increase the data model version" :)

**Comment by vpicavet** [comment]
Fixed the test.
@3nids ok to merge ?

**Comment by 3nids** [comment]
no objection on my side.
