### ISSUE TITLE
qwat_od.pipe :  too many recursive function call that end with a stack depth error

### ISSUE THREAD

**Issue by xaviermenetrey** [qwat/qwat-data-model#93]
Hello,

We are facing an issue when we try to insert a pipe (SQL below). 

`INSERT INTO qwat_od.pipe (id, fk_bedding, fk_function, fk_installmethod, fk_material, fk_distributor, fk_precision, fk_status, fk_watertype, pressure_nominal, "remark", "year", geometry) VALUES (14296,102,10002,103,102,5,1101,1301,1502,NULL,'Conduite de Lausanne (2")  non',1989,ST_GeomFromText('LINESTRINGZ(540900.2686702100 152955.4115092800 0.0, 540900.4100672200 152952.3142217600 0.0)',21781))`

This insert triggers too many recursive function call that end with a stack depth error as below.

> ERREUR:  dépassement de limite (en profondeur) de la pile
HINT:  Augmenter le paramètre « max_stack_depth » (actuellement 3072 Ko) après vous
être assuré que la limite de profondeur de la pile de la plateforme est
adéquate.
CONTEXT:  instruction SQL « SELECT qwat_od.fn_node_create(ST_StartPoint(NEW.geometry)) »
fonction PL/pgsql qwat_od.ft_pipe_geom(), ligne 3 à affectation
instruction SQL « UPDATE qwat_od.pipe SET geometry = ST_Snap(geometry, NEW.geometry, 1e-6) WHERE ST_Distance(geometry, NEW.geometry) < 1e-6 »
fonction PL/pgsql qwat_od.ft_node_geom(), ligne 22 à instruction SQL
instruction SQL « INSERT INTO qwat_od.node (geometry) VALUES (ST_Force3D(_point)) RETURNING id »
fonction PL/pgsql qwat_od.fn_node_create(geometry), ligne 7 à instruction SQL
instruction SQL « SELECT qwat_od.fn_node_create(ST_EndPoint(  NEW.geometry)) »
fonction PL/pgsql qwat_od.ft_pipe_geom(), ligne 4 à affectation
instruction SQL « UPDATE qwat_od.pipe SET geometry = ST_Snap(geometry, NEW.geometry, 1e-6) WHERE ST_Distance(geometry, NEW.geometry) < 1e-6 »
fonction PL/pgsql qwat_od.ft_node_geom(), ligne 22 à instruction SQL
instruction SQL « INSERT INTO qwat_od.node (geometry) VALUES (ST_Force3D(_point)) RETURNING id »
fonction PL/pgsql qwat_od.fn_node_create(geometry), ligne 7 à instruction SQL
instruction SQL « SELECT qwat_od.fn_node_create(ST_EndPoint(  NEW.geometry)) »
fonction PL/pgsql qwat_od.ft_pipe_geom(), ligne 4 à affectation
...

Is there a way to detect and prevent recursive loops ?
The geometry of the pipe doesn't seem complex...

**Comment by 3nids** [comment]
This is introduced by the new trigger to add vertices when placing valve (or any network element)
https://github.com/qwat/qwat-data-model/commit/7d1eede37beb5fc88d7cb851327b0accea49c638

@mhugo I suppose this can be solved by checking that the point does not intersect with start or end point of the pipe. What do you think? Do you take care of this?

**Comment by mhugo** [comment]
Yes, I'll have a look

**Comment by xaviermenetrey** [comment]
Hello,
 
I tested your fix, unfortunately it doesn't work.

I get the same error with the same pipe.

**Comment by mhugo** [comment]
@xaviermenetrey @3nids I can't reproduce and I am not sure to understand what the problem is ...
Could you give me some SQL instructions to reproduce the issue from an empty qwat database ?

**Comment by xaviermenetrey** [comment]
From an empty run :

`INSERT INTO qwat_od.pipe (id, fk_bedding, fk_function, fk_installmethod, fk_material, fk_distributor, fk_precision, fk_status, fk_watertype, pressure_nominal,geometry,"remark", "year") VALUES (14428,102,10005,103,10060,5,1101,1301,1502,NULL,ST_GeomFromText('LINESTRINGZ(540899.7448098600 152955.6844859300 0.0, 540900.2657501200 152955.5342266400 0.0, 540900.2686702100 152955.4115092600 0.0)',21781),'Conduite de Lausanne (2"1/2)  non',1989)`


Then :

`INSERT INTO qwat_od.pipe (id, fk_bedding, fk_function, fk_installmethod, fk_material, fk_distributor, fk_precision, fk_status, fk_watertype, pressure_nominal, "remark", "year", geometry) VALUES (14296,102,10002,103,102,5,1101,1301,1502,NULL,'Conduite de Lausanne (2") non',1989,ST_GeomFromText('LINESTRINGZ(540900.2686702100 152955.4115092800 0.0, 540900.4100672200 152952.3142217600 0.0)',21781))`

It will produce the error.

**Comment by 3nids** [comment]
there is a circular dependency due to @mhugo addition.
I will try to decouple the trigger (pipe and node geom).
