### ISSUE TITLE
Consider droping the _length2d pipe column in favor of a virtual field

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#96]
Advantages: 
- a pipe that's not saved will have the length already calculated on the QGIS side
- dropping a column that's somewhat redundant as we can calculate it
- shrinks the pipe data transferred over the network (just a little bit but still..)

I don't see any disadvantages at the moment.

In the future, when a 3d length expression would be available, we may consider dropping the _length3d column also.

Thoughts?

**Comment by tudorbarascu** [comment]
On the Desktop side, I haven't seen any performance penalty using 17 000 pipes while adding a virtual field that does the above.

**Comment by 3nids** [comment]
I don't really mind, indeed it can be removed.

For 3d, not sure yet, I have to write down some proposition on how to handle 3d in nodes and pipes.

**Comment by 3nids** [comment]
see #105
