### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by mhugo** [qwat/qwat-data-model#97]
After a fresh pull, I have the following error executing init_qwat.sh :

<pre>
...
CREATE RULE
CREATE RULE
CREATE VIEW
CREATE VIEW
COMMENT
CREATE RULE
CREATE VIEW
COMMENT
CREATE TRIGGER
ERREUR:  erreur de syntaxe sur ou près de « ( »
LIGNE 29 : ...LESCE(element.orientation, node._pipe_orientation)(element.o...
</pre>

**Comment by 3nids** [comment]
The submodule metaproject was updated. It should be updated too.

**Comment by mhugo** [comment]
Indeed my metaproject was out of sync
