### ISSUE TITLE
regression

### ISSUE THREAD

**Issue by mhugo** [qwat/qwat-data-model#98]
The unit tests I wrote to test vertex addition issues are now broken ...

Could we agree to use them and make sure they run when modifying the model ? (waiting for a Travis CI integration)

<pre>
-psql:/home/hme/src/QWAT/data-model/tests/test_add_node.sql:26: ERROR:  relation "qwat_od.vw_element_valve" does not exist
-LIGNE 1 : INSERT INTO qwat_od.vw_element_valve (id, fk_district, fk_pr...
</pre>

**Comment by 3nids** [comment]
trying to fix them, I adapted them to 3D but it doesn't seem enough

**Comment by mhugo** [comment]
Ok now that the init is ok, I will fix them and integrate the fix for #93

**Comment by mhugo** [comment]
Fixed in 220df957d
